# yaml-language-server: $schema=https://coderabbit.ai/integrations/schema.v2.json
language: "en"

tone_instructions: "Be thorough and professional in code reviews. Focus on security, performance, and maintainability."

reviews:
  profile: "assertive"
  request_changes_workflow: true
  high_level_summary: true
  review_status: true
  collapse_walkthrough: false
  poem: false
  
  path_filters:
    - "!node_modules/**"
    - "!.git/**"
    - "!dist/**"
    - "!build/**"
    - "!coverage/**"
    - "!*.lock"
    - "!*.min.js"
    - "!*.min.css"
    - "!.env*"
    - "!vendor/**"
    - "!__pycache__/**"
    - "!*.pyc"
    - "!.next/**"
    - "!.nuxt/**"
    - "src/**"
    - "lib/**"
    - "app/**"
    - "tests/**"
    - "**/*.js"
    - "**/*.ts"
    - "**/*.jsx"
    - "**/*.tsx"
    - "**/*.py"
    - "**/*.go"
    - "**/*.rs"
  
  path_instructions:
    - path: "**/*.js"
      instructions: |
        Review JavaScript code for:
        - Proper error handling with try-catch blocks
        - Input validation and sanitization
        - Security vulnerabilities (XSS, injection attacks)
        - Clean code principles (DRY, SOLID, KISS)
        - Performance optimizations
        - Proper authentication and authorization checks
        - No sensitive data exposure in logs
        - Consistent naming conventions
        - Comprehensive error messages
        - No unused imports or dead code
    - path: "**/*.ts"
      instructions: |
        Review TypeScript code for:
        - Proper type usage and type safety
        - Error handling with try-catch blocks
        - Input validation and sanitization
        - Security vulnerabilities
        - Clean code principles
        - Performance optimizations
        - Proper use of interfaces and types
    - path: "**/*.py"
      instructions: |
        Review Python code for:
        - Proper error handling
        - Input validation
        - Security vulnerabilities (SQL injection, XSS)
        - Following PEP 8 style guide
        - Proper docstrings and type hints
        - No secrets or credentials in code
    - path: "tests/**"
      instructions: |
        Review tests for:
        - Comprehensive test coverage
        - Descriptive test names
        - Proper test structure
        - Testing edge cases and error scenarios
  
  auto_review:
    enabled: true
    drafts: false
    base_branches: ["main", "master", "develop"]
  
  finishing_touches:
    docstrings:
      enabled: true
    unit_tests:
      enabled: true
  
  tools:
    eslint:
      enabled: true
    stylelint:
      enabled: true
    ruff:
      enabled: true
    pylint:
      enabled: true
    gitleaks:
      enabled: true
    trufflehog:
      enabled: true
    trivy:
      enabled: true
    semgrep:
      enabled: true
    checkov:
      enabled: true
    yamllint:
      enabled: true
    markdownlint:
      enabled: true
    shellcheck:
      enabled: true
    actionlint:
      enabled: true
    golangci-lint:
      enabled: true
    clippy:
      enabled: true
    flake8:
      enabled: true
    hadolint:
      enabled: true

knowledge_base:
  code_guidelines:
    enabled: true
  learnings:
    scope: "local"
